apiVersion: v1
kind: Namespace
metadata:
  name: ai-agent
  labels:
    purpose: agent-workload
    security-tier: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent-sa
  namespace: ai-agent
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::630243422167:role/ai-agent-security-lab-ai-agent-role
  labels:
    app: ai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-agent-role
  namespace: ai-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-agent-rolebinding
  namespace: ai-agent
subjects:
  - kind: ServiceAccount
    name: ai-agent-sa
    namespace: ai-agent
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: ai-agent-role
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-agent-network-policy
  namespace: ai-agent
spec:
  podSelector:
    matchLabels:
      app: ai-agent
  policyTypes:
    - Ingress
    - Egress
  ingress:
    []
  egress:
    - ports:
        - port: 53
          protocol: UDP
    - ports:
        - port: 443
          protocol: TCP
    - ports:
        - port: 6443
          protocol: TCP